name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '.dockerignore'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      id: install-deps
      run: |
        pip install -r requirements.txt

    - name: Check Pylint
      id: pylint-check
      run: |
        python -m pylint ./src
